version:   '2'

services:
  website:
    image: 'docker.io/bitnami/symfony:1-debian-10'
    ports:
      - '8000:8000'
      - '3306:3306'
    volumes:
      - '.:/app'
    environment:
      - SYMFONY_PROJECT_NAME=sym_sys
    depends_on:
      - nerdy_db
  nerdy_db:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=127.0.0.1
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_PASSWORD=root123
      - MARIADB_USER=test
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=nerdy
